name: Movie Project - Backend - CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: |
        python -m pip install pipenv

    - name: Install Dependencies
      run: |
        cd starter/backend
        pipenv install
    
    - name: Install flake8
      run: |
        cd starter/backend
        pipenv run pip install flake8

    - name: Lint Code
      run: |
        cd starter/backend
        pipenv run flake8

    - name: Lint Code
      run: |
        cd starter/backend
        pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: |
        python -m pip install pipenv

    - name: Install Dependencies
      run: |
        cd starter/backend
        pipenv install

    - name: Run Tests
      run: |
        cd starter/backend
        pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: |
        python -m pip install pipenv

    - name: Install Dependencies
      run: |
        cd starter/backend
        pipenv install

    - name: Install flake8
      run: |
        cd starter/backend
        pipenv run pip install flake8

    - name: Lint Code
      run: |
        cd starter/backend
        pipenv run flake8

    - name: Lint Code (Fail Workflow on Lint Failure)
      run: |
        cd starter/backend
        pipenv run lint-fail
      continue-on-error: true  # Continue the workflow even if linting fails

    - name: Fail Workflow on Lint Failure
      if: ${{ failure() }}  # This step will only run if the previous step failed
      run: exit 1  # Exit the workflow with a failure status code

    - name: Build Docker App
      run: |
        cd starter/backend
        docker build -t frontend .